---
apiVersion: v1
kind: Service
metadata:
  name: $CIRCLE_PROJECT_REPONAME
  labels:
    name: $CIRCLE_PROJECT_REPONAME
  annotations:
    external-dns.alpha.kubernetes.io/hostname: ${CIRCLE_PROJECT_REPONAME}.${NAMESPACE}.${CLUSTER}.${DOMAIN}
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: ${SSL}
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
  labels:
    k8s-addon: ingress-nginx.addons.k8s.io
spec:
  type: LoadBalancer
  ports:
  - port: 443
    name: https
    targetPort: 80
  - port: 80
    name: http
    targetPort: 8080
  selector:
    name: $CIRCLE_PROJECT_REPONAME
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: $CIRCLE_PROJECT_REPONAME
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: $CIRCLE_PROJECT_REPONAME
        service: $CIRCLE_PROJECT_REPONAME
    spec:
      hostname: $CIRCLE_PROJECT_REPONAME
      subdomain: $CIRCLE_PROJECT_REPONAME
      containers:
      - image: ${AWS_ACCOUNT_ID}.dkr.ecr.ap-southeast-2.amazonaws.com/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}
        name: $CIRCLE_PROJECT_REPONAME
        ports:
        - containerPort: 80
          name: $CIRCLE_PROJECT_REPONAME
